### ISSUE TITLE
Pre-requisites

### ISSUE THREAD

**Issue by Anuragtech02** [IET-DAVV/website-client#28]

**Comment by aakanksha32173** [comment]
**JavaScript**
JavaScript is high-level, often just-in-time compiled, and multi-paradigm. It has curly-bracket syntax, dynamic typing, prototype-based object-orientation, and first-class functions.
**TypeScript**
TypeScript is a typed superset of JavaScript that compiles to plain JavaScript. TypeScript is pure object oriented with classes, interfaces and statically typed like C# or Java.it gives an option to the compiler to whether or not to include data types associated with the variables or it basically allows us to make the compiler unaware of the type of data or variables.
**Next.js**
Next.js is a React framework that allows you to build supercharged, SEO-friendly, and extremely user-facing static websites and web applications using the React framework. It has hybrid static and server rendering, TypeScript support, smart bundling, route prefetching, and more, with no extra configuration needed.
