### ISSUE TITLE
How to create an issue

### ISSUE THREAD

**Issue by Anuragtech02** [IET-DAVV/website-client#31]

**Comment by manasbhandari** [comment]
1.On GitHub.com, navigate to the main page of the repository.
2.Under your repository name, click  Issues.
3.Click New issue
4.If your repository uses issue templates, click Get started next to the type of issue you'd like to open.
Or, click Open a blank issue if the type of issue you'd like to open isn't included in the available options.
5.Type a title and description for your issue.
6.When you're finished, click Submit new issue.
