### ISSUE TITLE
How to create a PR

### ISSUE THREAD

**Issue by Anuragtech02** [IET-DAVV/website-client#32]

**Comment by manasbhandari** [comment]
1.To create a pull request, you need to have made your code changes on a separate branch or forked repository.
2.open repository,  Pull request in the option available in the horizontal navbar .
3.Select create pull request button
4..Select the branch from which you are creating the PR.
5.After creating a pull request, you can modify its description or anything else on the form by selecting Edit on the pull request's page.

To change the PR name according to functionality (like feature added or bug fixes ) 
go to the edit option button on top  right corner of the pull request and rename  it according to given below...
for features added - [FEAT]
for bug fixes - [BUG]
for suggestion - [SUGGESTION]
![WhatsApp Image 2022-11-24 at 18 43 58](https://user-images.githubusercontent.com/107706027/203793202-d0a4afaa-2c6c-45a7-8025-50ed5dbe4583.jpeg)
